### ISSUE TITLE
Brak danych

### ISSUE THREAD

**Issue by pidzej** [bogdal/django-gusregon#1]
Po wprowadzeniu klucza i zmianie na środowisko testowe ( https://wyszukiwarkaregon**test**.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc ) oraz użyciu przykładu z repo nip wprowadzony w formularz nie zwraca danych.  

z api dostaje zwrot : u''

**Comment by bogdal** [comment]
Dla środowiska testowego kluczem użytkownika jest [aaaaaabbbbbcccccdddd](https://github.com/bogdal/django-gusregon/blob/master/gusregon/gus.py#L29):
```
data = {'pKluczUzytkownika': 'aaaaaabbbbbcccccdddd'}
```
